saturday are closed
sunday are closed


2021/01/01 is closed   /' Neujahr  '/
2021/01/06 is closed   /' Heilige Drei Könige  '/
2021/04/02 is closed   /' Karfreitag  '/
2021/04/05 is closed   /' Ostern - Ostermontag  '/
2021/05/01 is closed   /' 1. Mai - Tag der Arbeit  '/
2021/05/13 is closed   /' Christi Himmelfahrt  '/
2021/05/24 is closed   /' Pfingsten - Pfingstmontag  '/
2021/06/03 is closed   /' Fronleichnam  '/
2021/10/03 is closed   /' Tag der Deutschen Einheit  '/
2021/11/01 is closed   /' Allerheiligen  '/
2021/12/25 is closed   /' 1. Weihnachtsfeiertag  '/
2021/12/26 is closed   /' 2. Weihnachtsfeiertag  '/


2021/12/24 is closed    /' Weihnachten  '/

2021/12/31 is closed    /' Silvester  '/

