
2022/01/01 is closed  /' Neujahr  '/
2022/01/06 is closed  /' Heilige Drei Könige  '/
2022/04/15 is closed  /' Karfreitag  '/
2022/04/18 is closed  /' Ostern - Ostermontag  '/
2022/05/01 is closed  /' 1. Mai - Tag der Arbeit  '/
2022/05/26 is closed  /' Christi Himmelfahrt  '/
2022/06/06 is closed  /' Pfingsten - Pfingstmontag  '/
2022/06/16 is closed  /' Fronleichnam  '/
2022/10/03 is closed  /' Tag der Deutschen Einheit  '/
2022/11/01 is closed  /' Allerheiligen  '/
2022/02/05 is closed  /' 1. Weihnachtsfeiertag  '/
2022/12/26 is closed  /' 2. Weihnachtsfeiertag  '/

